### ISSUE TITLE
Add tracking

### ISSUE THREAD

**Issue by doublejosh** [tableau-mkt/liftigniter#16]
Tracking allows the liftIgniter system to gain insight on good recommendations, and allows you access to data in their dashboard.

### Details
Here's the code that would need to be added to liftigniter.js
```javascript
// Add tracking.
$p('track', {
  elements: document.querySelectorAll('li.recommended-item'),
  name: 'my-widget',
  source: 'LI',
  _debug: false
});
```

This includes some BEM changes that need to happen in the Mustache template.

**Relies On:** https://github.com/tableau-mkt/www7/pull/1463

**Comment by pvanoverbeek** [comment]
@doublejosh Same for this one. Are you active on this or can we update to reflect closed or not being actively worked on?

**Comment by doublejosh** [comment]
This is actually ready for merge.  We decided to toss in a bug fix as well.
