### ISSUE TITLE
Bug: Underscore on Customer Story Liftigniter recommendations

### ISSUE THREAD

**Issue by pvanoverbeek** [tableau-mkt/liftigniter#18]
![ssss](https://cloud.githubusercontent.com/assets/13735811/15872417/2ed4f22e-2cae-11e6-8436-51c300293092.JPG)

Underscore seen in Customer Story Liftigniter recomendations. repro on this page: http://www.tableau.com/learn/webinars/tableau-10-virtual-user-group

**Comment by doublejosh** [comment]
Believe this popped up after the content type name was recently translated.

**Comment by doublejosh** [comment]
Issue moved to [tableau-mkt/www7 #3331](https://github.com/tableau-mkt/www7/issues/3331) via [**ZenHub.io**](https://www.zenhub.io/)
